/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/hospital_room/bed.glb --transform 
Files: ./public/models/hospital_room/bed.glb [21.37MB] > /Users/cex/Desktop/projects/RxVR-R3F/bed-transformed.glb [503.53KB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WardBed(props) {
  const { nodes, materials } = useGLTF('/models/hospital_room/bed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Sign-material003'].geometry} material={materials.Sign} position={[0.004, 0.203, 0.261]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['IvPole-material002'].geometry} material={materials.IvPole} position={[0.042, 0, 0.149]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['Serum-material003'].geometry} material={materials.Serum} position={[0.042, 0.193, 0.117]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['Commode-material002'].geometry} material={materials.Commode} position={[0.038, 0, -0.167]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['FoodTable-material002'].geometry} material={materials.FoodTable} position={[0.107, 0.038, -0.275]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh
        geometry={nodes['ElectricSystm-material003'].geometry}
        material={materials.ElectricSystm}
        position={[-0.01, 0.207, 0.007]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.001}
      />
      <mesh geometry={nodes['TvSystm-material002'].geometry} material={materials.TvSystm} position={[-0.008, 0.24, 0.062]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['Tv-material003'].geometry} material={materials.material_8} position={[0.048, 0.388, 0.061]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['Light1-material003'].geometry} material={materials.Light1} position={[0.002, 0.445, 0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['Light2-material003'].geometry} material={materials.Light2} position={[0.002, 0.445, 0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['Bed-material002'].geometry} material={materials.material} position={[0.17, 0.045, 0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/models/hospital_room/bed-transformed.glb')
