/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/buildings/buildings.gltf --transform 
Files: ./public/models/buildings/buildings.gltf [12.33KB] > /Users/cex/Desktop/projects/RxVR-R3F/buildings-transformed.glb [4.62KB] (63%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Buildings(props) {
  const { nodes, materials } = useGLTF('/models/buildings/buildings-transformed.glb')
  return (
    <RigidBody colliders='trimesh' type='fixed'>
      <group {...props} dispose={null}>
        <group scale={[3,0.5,3]}>
          <mesh geometry={nodes.Cork_University_Hospital_1.geometry} material={materials.wall} />
          <mesh geometry={nodes.Cork_University_Hospital_2.geometry} material={materials.roof} />
        </group>
        <group scale={[3,2.5,3]} position-y={4.8}>
          <mesh geometry={nodes.Cork_University_Hospital_1.geometry} material={materials.wall} />
          <mesh geometry={nodes.Cork_University_Hospital_2.geometry} material={materials.roof} />
        </group>

      </group>

    </RigidBody>
    
  )
}

useGLTF.preload('/buildings-transformed.glb')
