/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/buildings/buildings.gltf --transform 
Files: ./public/models/buildings/buildings.gltf [13.58KB] > /Users/cex/Desktop/projects/RxVR-R3F/buildings-transformed.glb [5.41KB] (60%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Buildings(props) {
  const { nodes, materials } = useGLTF('/models/buildings/buildings-transformed.glb')
  console.log(nodes)
  return (
    <group {...props} dispose={null} scale={3}>
      <group>
        <mesh geometry={nodes.Cork_University_Hospital_1.geometry} material={materials.wall} />
        <mesh geometry={nodes.Cork_University_Hospital_2.geometry} material={materials.roof} />
      </group>
    </group>
  )
}

useGLTF.preload('/buildings-transformed.glb')
