/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/hospital-hall/hospital-hall.glb --transform 
Files: ./public/models/hospital-hall/hospital-hall.glb [44.79MB] > /Users/cex/Desktop/projects/RxVR-R3F/hospital-hall-transformed.glb [3.17MB] (93%)
Author: flaviafabbri (https://sketchfab.com/flaviafabbri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hospital-hall-ed4081584d0b4a3c8074daa436e1bab6
Title: Hospital hall
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HospitalHall(props) {
  const { nodes, materials } = useGLTF('/models/hospital-hall/hospital-hall-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['003_���������������001_0'].geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes['36fasdas2097_Material_#2142146565_0'].geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes['Cylinder34500_11_-_yyDefault_0'].geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.IMAC_SCRE224_Material004_0.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.IMAC_SCRE225_Material003_0.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Line2029228546_Material005_0.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes['Loft81_proxy018_���������������001_0'].geometry} material={materials['.001_1']} />
      <mesh geometry={nodes['Obj3d66-369784-10-155_Mat3d66-369784-1-522001_0'].geometry} material={materials['Mat3d66-369784-1-522.001']} />
      <mesh geometry={nodes['Obj3d66-369784-17-488_Mat3d66-369784-4-106001_0'].geometry} material={materials['Mat3d66-369784-4-106.001']} />
      <mesh geometry={nodes['Obj3d66-369784-18-731_Mat3d66-369784-3-210001_0'].geometry} material={materials['Mat3d66-369784-3-210.001']} />
      <mesh geometry={nodes['Obj3d66-369784-19-490_Mat3d66-369784-5-836001_0'].geometry} material={materials['Mat3d66-369784-5-836.001']} />
      <mesh geometry={nodes['Obj3d66-369784-53-956_Mat3d66-369784-2-684001_0'].geometry} material={materials['Mat3d66-369784-2-684.001']} />
      <mesh geometry={nodes['Obj3d66-369784-79-026_Material_#2146024216_0'].geometry} material={materials.Material_2146024216} />
      <mesh geometry={nodes['Obj3d66-817361-325-054_Mat3d66-817361-24-1947001_0'].geometry} material={materials.PaletteMaterial004} />
      <mesh geometry={nodes['Rectangle001_Material_#25_0'].geometry} material={materials.Material_25} />
      <mesh geometry={nodes['Rectangle002_Material_#26_0'].geometry} material={materials.Material_26} />
      <mesh geometry={nodes.Rectangle2123437283_Material001_0.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes['Rectangle307_Material_#31_0'].geometry} material={materials.PaletteMaterial005} />
      <mesh geometry={nodes['Rectangle344_Material_#2100466332_0'].geometry} material={materials.Material_2100466332} />
      <mesh geometry={nodes['Rectangle382_Material_#2100466335_0'].geometry} material={materials.Material_2100466335} />
      <mesh
        geometry={nodes.Plane_zrcadlo_0.geometry}
        material={materials.PaletteMaterial006}
        position={[-23.149, 1.775, -10.261]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.609}
      />
      <mesh geometry={nodes['Ellipse005_���������092hhr002_0'].geometry} material={materials['0.92hhr.002']} />
    </group>
  )
}

useGLTF.preload('/models/hospital-hall/hospital-hall-transformed.glb')
