/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/sliding-door/sliding-door.gltf --transform 
Files: ./public/models/sliding-door/sliding-door.gltf [10.55KB] > /Users/cex/Desktop/projects/RxVR-R3F/sliding-door-transformed.glb [7.88KB] (25%)
Author: ROY (https://sketchfab.com/roy.gearloft.in)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sliding-door-c8d08012886f49798a0fb5ffbd5b2feb
Title: Sliding Door
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SlidingDoor(props) {
  const { nodes, materials } = useGLTF('/models/sliding-door/sliding-door-transformed.glb')
  console.log(nodes)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Ebony_mat} position={[0, 1.355, 0]} scale={0.009} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Window_Mat} position={[0, 1.355, 0]} scale={0.009} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Silver_mat} position={[0.857, 0.856, -0.025]} scale={0.009} />
    </group>
  )
}

useGLTF.preload('/models/sliding-door/sliding-door-transformed.glb')
