// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.16 ./public/models/knight/knight.glb --transform 
// Files: ./public/models/knight/knight.glb [312.68KB] > /Users/cex/Desktop/projects/RxVR-R3F/knight-transformed.glb [31.35KB] (90%)
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Knight(props) {
//   const { nodes, materials } = useGLTF('/models/knight/knight-transformed.glb')
//   return (
//     <group {...props} dispose={null} position={[-5, 5, 0]}>
//       <primitive object={nodes.Root} />
//       <primitive object={nodes.IKLegPoleL} />
//       <primitive object={nodes.IKTargetL} />
//       <primitive object={nodes.IKLegPoleR} />
//       <primitive object={nodes.IKTargetR} />
//       <skinnedMesh geometry={nodes.Knight.geometry} material={materials.Knight} skeleton={nodes.Knight.skeleton} position={[27.723, -3.43, -7.511]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={38.575} />
//     </group>
//   )
// }

// useGLTF.preload('/knight-transformed.glb')
