// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.16 ./public/models/robot/robot.glb --transform 
// Files: ./public/models/robot/robot.glb [401.02KB] > /Users/cex/Desktop/projects/RxVR-R3F/robot-transformed.glb [149.56KB] (63%)
// */

// import React, { useRef } from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'

// export function Robot(props) {
//   const group = useRef()
//   const { nodes, materials, animations } = useGLTF('/models/robot/robot-transformed.glb')
//   const { actions } = useAnimations(animations, group)
//   return (
//     <group ref={group} {...props} dispose={null} scale={0.5} position={[3,3,3]}>
//       <group name="Root_Scene">
//         <primitive object={nodes.Bone} />
//         <group name="HandR" position={[-0.003, 2.37, -0.021]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//           <skinnedMesh name="HandR_1" geometry={nodes.HandR_1.geometry} material={materials.Main} skeleton={nodes.HandR_1.skeleton} />
//           <skinnedMesh name="HandR_2" geometry={nodes.HandR_2.geometry} material={materials.Grey} skeleton={nodes.HandR_2.skeleton} />
//         </group>
//         <group name="HandL" position={[-0.003, 2.37, -0.021]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//           <skinnedMesh name="HandL_1" geometry={nodes.HandL_1.geometry} material={materials.Main} skeleton={nodes.HandL_1.skeleton} />
//           <skinnedMesh name="HandL_2" geometry={nodes.HandL_2.geometry} material={materials.Grey} skeleton={nodes.HandL_2.skeleton} />
//         </group>
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/robot-transformed.glb')
